### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by EaZyStudiio** [loilo/ico2png-cli#11]
![Taskmgr_d9iNj0r97Z](https://user-images.githubusercontent.com/55167211/153869928-ad006074-217e-49b2-85cd-baee44b24b7a.png)

I can't get the converter to work  see the image below for the  error

Am using node 17. 

And Using MSVS 2019 and 22 

![WindowsTerminal_zRLXUKbWHm](https://user-images.githubusercontent.com/55167211/153870478-807e2558-3c87-4c75-b2b6-71940b7526ae.png)

Quick note I don't do JS I am just in need of this specific tool 😢.

**Comment by loilo** [comment]
Whoa, that's quite some memory consumption. Is it a particularly large ICO file? (Could you attach it? That would help debugging a lot.)

**Comment by loilo** [comment]
@Eazy5d Feel free to provide more information if you're ready, I'll close this issue as stale for now.
